# Generated by Django 4.1.7 on 2023-03-05 15:03

from django.db import migrations, models
import quizapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['score']},
        ),
        migrations.AddField(
            model_name='profile',
            name='lastQuestionTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='question_id',
            field=models.IntegerField(default=1, verbose_name='Question At'),
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_questions',
            field=models.IntegerField(default=quizapp.models.Profile.question_count, verbose_name='Total Questions'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.png', null=True, upload_to='user_data'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
