# Generated by Django 4.1.7 on 2023-03-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
