# Generated by Django 4.1.7 on 2023-03-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_profile_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-score']},
        ),
        migrations.AddField(
            model_name='profile',
            name='data',
            field=models.TextField(default='March 6, 2023 10:00:00'),
        ),
    ]
