# Generated by Django 3.2.15 on 2023-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_alter_profile_options_profile_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeriedEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('is_player', models.BooleanField(default=False)),
            ],
        ),
    ]
