# Generated by Django 3.2.15 on 2023-04-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_veriedemails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VeriedEmails',
            new_name='VerifiedEmails',
        ),
    ]
