# Generated by Django 3.2.18 on 2023-04-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_rename_veriedemails_verifiedemails'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifedEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('is_player', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='VerifiedEmails',
        ),
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=models.TextField(default='April 12, 2023 18:00:00'),
        ),
    ]
