# Generated by Django 3.2.18 on 2023-04-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_auto_20230411_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifedEmails',
            new_name='VerifiedEmails',
        ),
    ]
